In [ ]:
import numpy as np
words = ["the","cat","sat","on","the","mat"]
vocab = sorted(set(words))
print("Vocabulary:",vocab)

Vocabulary: ['cat', 'mat', 'on', 'sat', 'the']


In [ ]:
word_to_index = {word: i for i, word in enumerate(vocab)}
print("\nWord to Index Mapping:",word_to_index)


Word to Index Mapping: {'cat': 0, 'mat': 1, 'on': 2, 'sat': 3, 'the': 4}


In [ ]:
num_words = len(words)
vocab_size = len(vocab)
one_hot_matrix = np.zeros((num_words, vocab_size), dtype=int)
for i, word in enumerate(words):
    index = word_to_index[word]
    one_hot_matrix[i, index] = 1

In [ ]:
print("\nOne-Hot Encoding Matrix:")
print(one_hot_matrix)


One-Hot Encoding Matrix:
[[0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]]


In [ ]:
for i, word in enumerate(words):
    print(word, "->", one_hot_matrix[i])

the -> [0 0 0 0 1]
cat -> [1 0 0 0 0]
sat -> [0 0 0 1 0]
on -> [0 0 1 0 0]
the -> [0 0 0 0 1]
mat -> [0 1 0 0 0]


In [ ]:
import numpy as np
text = "hello"

chars = sorted(set(text))
print("Characters:", chars)

Characters: ['e', 'h', 'l', 'o']


In [ ]:
char_to_index = {ch: i for i, ch in enumerate(chars)}
print("Character to Index Mapping:", char_to_index)

Character to Index Mapping: {'e': 0, 'h': 1, 'l': 2, 'o': 3}


In [ ]:
one_hot_chars = np.zeros((len(text), len(chars)), dtype=int)

for i, ch in enumerate(text):
    index = char_to_index[ch]
    one_hot_chars[i, index] = 1

print("\nOne-Hot Encoded Chars:")
print(one_hot_chars)


One-Hot Encoded Chars:
[[0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
print("\nOne-Hot Encoded Chars:")
for i, ch in enumerate(text):
    print(f"{ch} -> {one_hot_chars[i]}")


One-Hot Encoded Chars:
h -> [0 1 0 0]
e -> [1 0 0 0]
l -> [0 0 1 0]
l -> [0 0 1 0]
o -> [0 0 0 1]
